-- Généré depuis « MFWA Institutional Development Documents.xlsx » (onglet « MFWA Key docs »).
-- Idempotent : peut être ré-exécuté sans dupliquer les lignes.

SET @import_user := (SELECT id FROM users ORDER BY id LIMIT 1);

-- 38 documents
INSERT INTO key_documents (category_id, title, status, year_label, produced_label, produced_year, reviewed_on, reviewed_year, review_label, drive_url, comment, sort_order, created_by) SELECT (SELECT id FROM key_document_categories WHERE name = 'Registration documents'), 'Certificate of Incorporation', 'available', '2025', '1997/2016', NULL, NULL, 2025, NULL, 'https://drive.google.com/file/d/1awiisyxK-3TnRYi_vLrohmgyhc0pf1uM/view?usp=drive_link', NULL, 1, @import_user WHERE NOT EXISTS (SELECT 1 FROM key_documents WHERE title = 'Certificate of Incorporation' AND category_id = (SELECT id FROM key_document_categories WHERE name = 'Registration documents'));
INSERT INTO key_documents (category_id, title, status, year_label, produced_label, produced_year, reviewed_on, reviewed_year, review_label, drive_url, comment, sort_order, created_by) SELECT (SELECT id FROM key_document_categories WHERE name = 'Registration documents'), 'Certificate to Commence Business', 'available', '2025', '1997/2016', NULL, NULL, 2025, NULL, 'https://drive.google.com/file/d/1day_fgijWiTSdZMQ9xwqU-VAzKHMLSJZ/view?usp=sharing', NULL, 2, @import_user WHERE NOT EXISTS (SELECT 1 FROM key_documents WHERE title = 'Certificate to Commence Business' AND category_id = (SELECT id FROM key_document_categories WHERE name = 'Registration documents'));
INSERT INTO key_documents (category_id, title, status, year_label, produced_label, produced_year, reviewed_on, reviewed_year, review_label, drive_url, comment, sort_order, created_by) SELECT (SELECT id FROM key_document_categories WHERE name = 'Registration documents'), 'Non-Profit Organisation Certificate', 'available', '2026', '1997/2016', NULL, '2026-05-15', 2026, NULL, 'https://drive.google.com/file/d/1tctPz0DnDvXVPktV8QLNuQq-b8Fc4KYX/view?usp=sharing', NULL, 3, @import_user WHERE NOT EXISTS (SELECT 1 FROM key_documents WHERE title = 'Non-Profit Organisation Certificate' AND category_id = (SELECT id FROM key_document_categories WHERE name = 'Registration documents'));
INSERT INTO key_documents (category_id, title, status, year_label, produced_label, produced_year, reviewed_on, reviewed_year, review_label, drive_url, comment, sort_order, created_by) SELECT (SELECT id FROM key_document_categories WHERE name = 'Registration documents'), 'Adentan Municipal Assembly Certificate', 'available', '2026', '1997/2016', NULL, '2025-12-31', 2025, NULL, 'https://drive.google.com/file/d/1gQOtZArUarJJgnZHHSc8lGzQKovM3ev9/view?usp=sharing', NULL, 4, @import_user WHERE NOT EXISTS (SELECT 1 FROM key_documents WHERE title = 'Adentan Municipal Assembly Certificate' AND category_id = (SELECT id FROM key_document_categories WHERE name = 'Registration documents'));
INSERT INTO key_documents (category_id, title, status, year_label, produced_label, produced_year, reviewed_on, reviewed_year, review_label, drive_url, comment, sort_order, created_by) SELECT (SELECT id FROM key_document_categories WHERE name = 'Letterhead'), 'Old Letterhead', 'outdated', '1998', '1998', 1998, NULL, NULL, 'No longer in use', 'https://drive.google.com/file/d/1ZH4XHIblhx9TFE5FNY_egAir9CoUxyLw/view?usp=sharing', NULL, 5, @import_user WHERE NOT EXISTS (SELECT 1 FROM key_documents WHERE title = 'Old Letterhead' AND category_id = (SELECT id FROM key_document_categories WHERE name = 'Letterhead'));
INSERT INTO key_documents (category_id, title, status, year_label, produced_label, produced_year, reviewed_on, reviewed_year, review_label, drive_url, comment, sort_order, created_by) SELECT (SELECT id FROM key_document_categories WHERE name = 'Letterhead'), 'New Letter head', 'available', '2026', '2026', 2026, '2026-02-15', 2026, NULL, 'https://drive.google.com/file/d/1vqYxSNKTqTEoXF4INFC0ns0OQu8AIN31/view?usp=sharing', NULL, 6, @import_user WHERE NOT EXISTS (SELECT 1 FROM key_documents WHERE title = 'New Letter head' AND category_id = (SELECT id FROM key_document_categories WHERE name = 'Letterhead'));
INSERT INTO key_documents (category_id, title, status, year_label, produced_label, produced_year, reviewed_on, reviewed_year, review_label, drive_url, comment, sort_order, created_by) SELECT (SELECT id FROM key_document_categories WHERE name = 'Organogram'), 'Current Organisational Structure/Organogram', 'available', '2026', '2026', 2026, '2026-02-20', 2026, NULL, 'https://drive.google.com/file/d/1zmGZ5ZOCTLVp_Teul7SWq32Ht5u8w7pJ/view?usp=sharing', NULL, 7, @import_user WHERE NOT EXISTS (SELECT 1 FROM key_documents WHERE title = 'Current Organisational Structure/Organogram' AND category_id = (SELECT id FROM key_document_categories WHERE name = 'Organogram'));
INSERT INTO key_documents (category_id, title, status, year_label, produced_label, produced_year, reviewed_on, reviewed_year, review_label, drive_url, comment, sort_order, created_by) SELECT (SELECT id FROM key_document_categories WHERE name = 'Audited financial statements'), 'Audited Report for December 31, 2022, GHS', 'available', '2022', '2022-12-31', 2022, NULL, 2022, NULL, 'https://drive.google.com/file/d/1JmrUt1Zqa3yisdKBvndmCVOcKJ_UbPci/view?usp=sharing', NULL, 8, @import_user WHERE NOT EXISTS (SELECT 1 FROM key_documents WHERE title = 'Audited Report for December 31, 2022, GHS' AND category_id = (SELECT id FROM key_document_categories WHERE name = 'Audited financial statements'));
INSERT INTO key_documents (category_id, title, status, year_label, produced_label, produced_year, reviewed_on, reviewed_year, review_label, drive_url, comment, sort_order, created_by) SELECT (SELECT id FROM key_document_categories WHERE name = 'Audited financial statements'), 'Audited Report for December 31, 2023, GHS', 'available', '2023', '2023-12-31', 2023, NULL, 2023, NULL, 'https://drive.google.com/file/d/1w4wmumX9DpJAeDxPnZ1VnFFT8XntzquT/view?usp=sharing', NULL, 9, @import_user WHERE NOT EXISTS (SELECT 1 FROM key_documents WHERE title = 'Audited Report for December 31, 2023, GHS' AND category_id = (SELECT id FROM key_document_categories WHERE name = 'Audited financial statements'));
INSERT INTO key_documents (category_id, title, status, year_label, produced_label, produced_year, reviewed_on, reviewed_year, review_label, drive_url, comment, sort_order, created_by) SELECT (SELECT id FROM key_document_categories WHERE name = 'Audited financial statements'), 'Audited Report for December 31, 2024, GHS', 'available', '2024', '2024-12-31', 2024, NULL, 2024, NULL, 'https://drive.google.com/file/d/1j8asFl9f0aZ0k_6MWYd-bWGYMJqe3z3N/view?usp=sharing', NULL, 10, @import_user WHERE NOT EXISTS (SELECT 1 FROM key_documents WHERE title = 'Audited Report for December 31, 2024, GHS' AND category_id = (SELECT id FROM key_document_categories WHERE name = 'Audited financial statements'));
INSERT INTO key_documents (category_id, title, status, year_label, produced_label, produced_year, reviewed_on, reviewed_year, review_label, drive_url, comment, sort_order, created_by) SELECT (SELECT id FROM key_document_categories WHERE name = 'Audited financial statements'), 'Audited Report for December 31, 2025, GHS', 'in_review', '2025', '2025-12-31', 2025, NULL, 2025, NULL, 'https://drive.google.com/file/d/1blMcB-zAg-I5Szx-_Sjgvu8XlV55OhLY/view?usp=drive_link', 'Auditing being done', 11, @import_user WHERE NOT EXISTS (SELECT 1 FROM key_documents WHERE title = 'Audited Report for December 31, 2025, GHS' AND category_id = (SELECT id FROM key_document_categories WHERE name = 'Audited financial statements'));
INSERT INTO key_documents (category_id, title, status, year_label, produced_label, produced_year, reviewed_on, reviewed_year, review_label, drive_url, comment, sort_order, created_by) SELECT (SELECT id FROM key_document_categories WHERE name = 'Institutional policies'), 'Organisational Strategic Plan', 'available', '2025-2029', '2025', 2025, NULL, 2024, NULL, 'https://drive.google.com/file/d/1mWhghPg55gxpaizLCkLm6MowFhYgNQIy/view?usp=drive_link', NULL, 12, @import_user WHERE NOT EXISTS (SELECT 1 FROM key_documents WHERE title = 'Organisational Strategic Plan' AND category_id = (SELECT id FROM key_document_categories WHERE name = 'Institutional policies'));
INSERT INTO key_documents (category_id, title, status, year_label, produced_label, produced_year, reviewed_on, reviewed_year, review_label, drive_url, comment, sort_order, created_by) SELECT (SELECT id FROM key_document_categories WHERE name = 'Institutional policies'), 'Personnel and Admin Manual', 'available', '1999', '1999', 1999, NULL, 2019, NULL, 'https://drive.google.com/file/d/1YxwogKD7jLEd8IfY4tuWcOCL7TZ-ig_h/view?usp=sharing', NULL, 13, @import_user WHERE NOT EXISTS (SELECT 1 FROM key_documents WHERE title = 'Personnel and Admin Manual' AND category_id = (SELECT id FROM key_document_categories WHERE name = 'Institutional policies'));
INSERT INTO key_documents (category_id, title, status, year_label, produced_label, produced_year, reviewed_on, reviewed_year, review_label, drive_url, comment, sort_order, created_by) SELECT (SELECT id FROM key_document_categories WHERE name = 'Institutional policies'), 'Staff Code of Conduct', 'available', '2019', '2019', 2019, NULL, 2019, NULL, 'https://drive.google.com/file/d/1YSmM74kkST5xySphPcP1Yy8p_u2caR_7/view?usp=sharing', NULL, 14, @import_user WHERE NOT EXISTS (SELECT 1 FROM key_documents WHERE title = 'Staff Code of Conduct' AND category_id = (SELECT id FROM key_document_categories WHERE name = 'Institutional policies'));
INSERT INTO key_documents (category_id, title, status, year_label, produced_label, produced_year, reviewed_on, reviewed_year, review_label, drive_url, comment, sort_order, created_by) SELECT (SELECT id FROM key_document_categories WHERE name = 'Institutional policies'), 'Finanacial Management Policy, Structure and Systems', 'available', '2018', '2018', 2018, NULL, 2018, NULL, 'https://drive.google.com/file/d/1UbTThhKYt3vNq3hp1tfzyCbqVZcYsGLL/view?usp=drive_link', NULL, 15, @import_user WHERE NOT EXISTS (SELECT 1 FROM key_documents WHERE title = 'Finanacial Management Policy, Structure and Systems' AND category_id = (SELECT id FROM key_document_categories WHERE name = 'Institutional policies'));
INSERT INTO key_documents (category_id, title, status, year_label, produced_label, produced_year, reviewed_on, reviewed_year, review_label, drive_url, comment, sort_order, created_by) SELECT (SELECT id FROM key_document_categories WHERE name = 'Institutional policies'), 'M & E Policy', 'available', NULL, '2012', 2012, NULL, NULL, NULL, NULL, NULL, 16, @import_user WHERE NOT EXISTS (SELECT 1 FROM key_documents WHERE title = 'M & E Policy' AND category_id = (SELECT id FROM key_document_categories WHERE name = 'Institutional policies'));
INSERT INTO key_documents (category_id, title, status, year_label, produced_label, produced_year, reviewed_on, reviewed_year, review_label, drive_url, comment, sort_order, created_by) SELECT (SELECT id FROM key_document_categories WHERE name = 'Institutional policies'), 'Safeguarding Policy', 'available', NULL, '2020', 2020, NULL, NULL, NULL, 'https://drive.google.com/file/d/1ssIU7MbH7W-pXKQWN6oierQZmiiCKBGo/view?usp=sharing', NULL, 17, @import_user WHERE NOT EXISTS (SELECT 1 FROM key_documents WHERE title = 'Safeguarding Policy' AND category_id = (SELECT id FROM key_document_categories WHERE name = 'Institutional policies'));
INSERT INTO key_documents (category_id, title, status, year_label, produced_label, produced_year, reviewed_on, reviewed_year, review_label, drive_url, comment, sort_order, created_by) SELECT (SELECT id FROM key_document_categories WHERE name = 'Institutional policies'), 'Gender Policy', 'available', NULL, '2011', 2011, NULL, 2013, NULL, 'https://drive.google.com/file/d/1RZSPkx7Q0_eKKDaKazr1A2Vkn5uHWIce/view?usp=sharing', NULL, 18, @import_user WHERE NOT EXISTS (SELECT 1 FROM key_documents WHERE title = 'Gender Policy' AND category_id = (SELECT id FROM key_document_categories WHERE name = 'Institutional policies'));
INSERT INTO key_documents (category_id, title, status, year_label, produced_label, produced_year, reviewed_on, reviewed_year, review_label, drive_url, comment, sort_order, created_by) SELECT (SELECT id FROM key_document_categories WHERE name = 'Institutional policies'), 'Communications Strategy', 'available', NULL, '2012', 2012, NULL, NULL, NULL, NULL, NULL, 19, @import_user WHERE NOT EXISTS (SELECT 1 FROM key_documents WHERE title = 'Communications Strategy' AND category_id = (SELECT id FROM key_document_categories WHERE name = 'Institutional policies'));
INSERT INTO key_documents (category_id, title, status, year_label, produced_label, produced_year, reviewed_on, reviewed_year, review_label, drive_url, comment, sort_order, created_by) SELECT (SELECT id FROM key_document_categories WHERE name = 'Institutional policies'), 'Anti-Fraud Policy', 'available', NULL, '2025', 2025, NULL, NULL, NULL, 'https://drive.google.com/file/d/1knBOTsdeFozEi-07Jf_ODjYcVGgE4rVB/view?usp=sharing', NULL, 20, @import_user WHERE NOT EXISTS (SELECT 1 FROM key_documents WHERE title = 'Anti-Fraud Policy' AND category_id = (SELECT id FROM key_document_categories WHERE name = 'Institutional policies'));
INSERT INTO key_documents (category_id, title, status, year_label, produced_label, produced_year, reviewed_on, reviewed_year, review_label, drive_url, comment, sort_order, created_by) SELECT (SELECT id FROM key_document_categories WHERE name = 'Institutional policies'), 'Risk Management Policy', 'available', NULL, NULL, NULL, NULL, NULL, NULL, 'https://drive.google.com/file/d/1NbQnOLCJafhg5wX_o1_x1gvNWnmV1w3S/view?usp=sharing', NULL, 21, @import_user WHERE NOT EXISTS (SELECT 1 FROM key_documents WHERE title = 'Risk Management Policy' AND category_id = (SELECT id FROM key_document_categories WHERE name = 'Institutional policies'));
INSERT INTO key_documents (category_id, title, status, year_label, produced_label, produced_year, reviewed_on, reviewed_year, review_label, drive_url, comment, sort_order, created_by) SELECT (SELECT id FROM key_document_categories WHERE name = 'Institutional policies'), 'Whistle Blowing Policy', 'available', NULL, '2023', 2023, NULL, NULL, NULL, 'https://drive.google.com/file/d/1-0Ui2LvJbjx2Oh1wDlwstyhc5pWaP3P8/view?usp=sharing', NULL, 22, @import_user WHERE NOT EXISTS (SELECT 1 FROM key_documents WHERE title = 'Whistle Blowing Policy' AND category_id = (SELECT id FROM key_document_categories WHERE name = 'Institutional policies'));
INSERT INTO key_documents (category_id, title, status, year_label, produced_label, produced_year, reviewed_on, reviewed_year, review_label, drive_url, comment, sort_order, created_by) SELECT (SELECT id FROM key_document_categories WHERE name = 'Institutional policies'), 'Value For Money (VFM) Policy', 'available', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 23, @import_user WHERE NOT EXISTS (SELECT 1 FROM key_documents WHERE title = 'Value For Money (VFM) Policy' AND category_id = (SELECT id FROM key_document_categories WHERE name = 'Institutional policies'));
INSERT INTO key_documents (category_id, title, status, year_label, produced_label, produced_year, reviewed_on, reviewed_year, review_label, drive_url, comment, sort_order, created_by) SELECT (SELECT id FROM key_document_categories WHERE name = 'Institutional policies'), 'Performance Management Guidelines', 'available', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 24, @import_user WHERE NOT EXISTS (SELECT 1 FROM key_documents WHERE title = 'Performance Management Guidelines' AND category_id = (SELECT id FROM key_document_categories WHERE name = 'Institutional policies'));
INSERT INTO key_documents (category_id, title, status, year_label, produced_label, produced_year, reviewed_on, reviewed_year, review_label, drive_url, comment, sort_order, created_by) SELECT (SELECT id FROM key_document_categories WHERE name = 'Institutional policies'), 'Partnership Policy', 'available', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 25, @import_user WHERE NOT EXISTS (SELECT 1 FROM key_documents WHERE title = 'Partnership Policy' AND category_id = (SELECT id FROM key_document_categories WHERE name = 'Institutional policies'));
INSERT INTO key_documents (category_id, title, status, year_label, produced_label, produced_year, reviewed_on, reviewed_year, review_label, drive_url, comment, sort_order, created_by) SELECT (SELECT id FROM key_document_categories WHERE name = 'Institutional policies'), 'Data Protection Policy', 'available', NULL, '2023', 2023, NULL, NULL, NULL, 'https://drive.google.com/file/d/1dPC_aWO89c0CCFENJOf05GPuqBTwoNyU/view?usp=sharing', NULL, 26, @import_user WHERE NOT EXISTS (SELECT 1 FROM key_documents WHERE title = 'Data Protection Policy' AND category_id = (SELECT id FROM key_document_categories WHERE name = 'Institutional policies'));
INSERT INTO key_documents (category_id, title, status, year_label, produced_label, produced_year, reviewed_on, reviewed_year, review_label, drive_url, comment, sort_order, created_by) SELECT (SELECT id FROM key_document_categories WHERE name = 'Institutional policies'), 'MFWA Staff Welfare Constitution', 'available', NULL, NULL, NULL, NULL, 2025, NULL, 'https://drive.google.com/file/d/1lU_xZ6k4vlCaIuyX09ba-Ht_spwWIP52/view?usp=sharing', NULL, 27, @import_user WHERE NOT EXISTS (SELECT 1 FROM key_documents WHERE title = 'MFWA Staff Welfare Constitution' AND category_id = (SELECT id FROM key_document_categories WHERE name = 'Institutional policies'));
INSERT INTO key_documents (category_id, title, status, year_label, produced_label, produced_year, reviewed_on, reviewed_year, review_label, drive_url, comment, sort_order, created_by) SELECT (SELECT id FROM key_document_categories WHERE name = 'Institutional policies'), 'Asset Management Platform', 'missing', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 28, @import_user WHERE NOT EXISTS (SELECT 1 FROM key_documents WHERE title = 'Asset Management Platform' AND category_id = (SELECT id FROM key_document_categories WHERE name = 'Institutional policies'));
INSERT INTO key_documents (category_id, title, status, year_label, produced_label, produced_year, reviewed_on, reviewed_year, review_label, drive_url, comment, sort_order, created_by) SELECT (SELECT id FROM key_document_categories WHERE name = 'Institutional policies'), 'Staff and Skills Profiles', 'available', NULL, NULL, NULL, NULL, NULL, NULL, 'https://drive.google.com/drive/folders/19h47okqVYVaviaq-u840jySGasuIFMvl', NULL, 29, @import_user WHERE NOT EXISTS (SELECT 1 FROM key_documents WHERE title = 'Staff and Skills Profiles' AND category_id = (SELECT id FROM key_document_categories WHERE name = 'Institutional policies'));
INSERT INTO key_documents (category_id, title, status, year_label, produced_label, produced_year, reviewed_on, reviewed_year, review_label, drive_url, comment, sort_order, created_by) SELECT (SELECT id FROM key_document_categories WHERE name = 'Institutional policies'), 'MFWA Vendor and Consultants List', 'missing', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 30, @import_user WHERE NOT EXISTS (SELECT 1 FROM key_documents WHERE title = 'MFWA Vendor and Consultants List' AND category_id = (SELECT id FROM key_document_categories WHERE name = 'Institutional policies'));
INSERT INTO key_documents (category_id, title, status, year_label, produced_label, produced_year, reviewed_on, reviewed_year, review_label, drive_url, comment, sort_order, created_by) SELECT (SELECT id FROM key_document_categories WHERE name = 'Institutional policies'), 'MFWA Leave Policy', 'available', '2026', '2026', 2026, NULL, NULL, NULL, 'https://drive.google.com/file/d/1rZvVibDUUjBdvsDYHgT_s1OfR1lh28A0/view?usp=drive_link', NULL, 31, @import_user WHERE NOT EXISTS (SELECT 1 FROM key_documents WHERE title = 'MFWA Leave Policy' AND category_id = (SELECT id FROM key_document_categories WHERE name = 'Institutional policies'));
INSERT INTO key_documents (category_id, title, status, year_label, produced_label, produced_year, reviewed_on, reviewed_year, review_label, drive_url, comment, sort_order, created_by) SELECT (SELECT id FROM key_document_categories WHERE name = 'Institutional policies'), 'MFWA Travel Policy', 'available', '2026', '2026', 2026, NULL, NULL, NULL, 'https://drive.google.com/file/d/15i-IT7oYkFjm9pJtCeAJiIBGCNDdcIgn/view?usp=drive_link', NULL, 32, @import_user WHERE NOT EXISTS (SELECT 1 FROM key_documents WHERE title = 'MFWA Travel Policy' AND category_id = (SELECT id FROM key_document_categories WHERE name = 'Institutional policies'));
INSERT INTO key_documents (category_id, title, status, year_label, produced_label, produced_year, reviewed_on, reviewed_year, review_label, drive_url, comment, sort_order, created_by) SELECT (SELECT id FROM key_document_categories WHERE name = 'Institutional policies'), 'Due diligence Guidelines (downstream partners)', 'missing', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 33, @import_user WHERE NOT EXISTS (SELECT 1 FROM key_documents WHERE title = 'Due diligence Guidelines (downstream partners)' AND category_id = (SELECT id FROM key_document_categories WHERE name = 'Institutional policies'));
INSERT INTO key_documents (category_id, title, status, year_label, produced_label, produced_year, reviewed_on, reviewed_year, review_label, drive_url, comment, sort_order, created_by) SELECT (SELECT id FROM key_document_categories WHERE name = 'Institutional policies'), 'Capacity Assessment forms', 'missing', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 34, @import_user WHERE NOT EXISTS (SELECT 1 FROM key_documents WHERE title = 'Capacity Assessment forms' AND category_id = (SELECT id FROM key_document_categories WHERE name = 'Institutional policies'));
INSERT INTO key_documents (category_id, title, status, year_label, produced_label, produced_year, reviewed_on, reviewed_year, review_label, drive_url, comment, sort_order, created_by) SELECT (SELECT id FROM key_document_categories WHERE name = 'Institutional policies'), 'HR Manual', 'missing', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 35, @import_user WHERE NOT EXISTS (SELECT 1 FROM key_documents WHERE title = 'HR Manual' AND category_id = (SELECT id FROM key_document_categories WHERE name = 'Institutional policies'));
INSERT INTO key_documents (category_id, title, status, year_label, produced_label, produced_year, reviewed_on, reviewed_year, review_label, drive_url, comment, sort_order, created_by) SELECT (SELECT id FROM key_document_categories WHERE name = 'Institutional policies'), 'Procurement Policy', 'missing', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 36, @import_user WHERE NOT EXISTS (SELECT 1 FROM key_documents WHERE title = 'Procurement Policy' AND category_id = (SELECT id FROM key_document_categories WHERE name = 'Institutional policies'));
INSERT INTO key_documents (category_id, title, status, year_label, produced_label, produced_year, reviewed_on, reviewed_year, review_label, drive_url, comment, sort_order, created_by) SELECT (SELECT id FROM key_document_categories WHERE name = 'Institutional policies'), 'Staff training and Capacity development policy', 'missing', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 37, @import_user WHERE NOT EXISTS (SELECT 1 FROM key_documents WHERE title = 'Staff training and Capacity development policy' AND category_id = (SELECT id FROM key_document_categories WHERE name = 'Institutional policies'));
INSERT INTO key_documents (category_id, title, status, year_label, produced_label, produced_year, reviewed_on, reviewed_year, review_label, drive_url, comment, sort_order, created_by) SELECT (SELECT id FROM key_document_categories WHERE name = 'Institutional policies'), 'Previous program evaluation reports', 'missing', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 38, @import_user WHERE NOT EXISTS (SELECT 1 FROM key_documents WHERE title = 'Previous program evaluation reports' AND category_id = (SELECT id FROM key_document_categories WHERE name = 'Institutional policies'));

-- Actions issues des commentaires
INSERT INTO key_document_actions (document_id, text, created_by) SELECT (SELECT id FROM key_documents WHERE title = 'Adentan Municipal Assembly Certificate' LIMIT 1), 'Being renewed', @import_user WHERE NOT EXISTS (SELECT 1 FROM key_document_actions WHERE text = 'Being renewed' AND document_id = (SELECT id FROM key_documents WHERE title = 'Adentan Municipal Assembly Certificate' LIMIT 1));
INSERT INTO key_document_actions (document_id, text, created_by) SELECT (SELECT id FROM key_documents WHERE title = 'Organisational Strategic Plan' LIMIT 1), 'Need to rework the Strategic Objectives', @import_user WHERE NOT EXISTS (SELECT 1 FROM key_document_actions WHERE text = 'Need to rework the Strategic Objectives' AND document_id = (SELECT id FROM key_documents WHERE title = 'Organisational Strategic Plan' LIMIT 1));
INSERT INTO key_document_actions (document_id, text, created_by) SELECT (SELECT id FROM key_documents WHERE title = 'Staff Code of Conduct' LIMIT 1), 'Verify the year: the cover page says November 2019, source file was unsure that 2019 is correct', @import_user WHERE NOT EXISTS (SELECT 1 FROM key_document_actions WHERE text = 'Verify the year: the cover page says November 2019, source file was unsure that 2019 is correct' AND document_id = (SELECT id FROM key_documents WHERE title = 'Staff Code of Conduct' LIMIT 1));

-- 13 adhésions
INSERT INTO memberships (institution, year_commenced, last_renewed_year, renewed_label, status, reporting_cycle, renewal_cycle, fee_amount, fee_period, last_report_on, notes, created_by) SELECT 'UN- ECOSOC', 2016, NULL, NULL, 'active', 'Quadrennial', 'Every 4 years', NULL, 'multi_year', '2026-06-01', NULL, @import_user WHERE NOT EXISTS (SELECT 1 FROM memberships WHERE institution = 'UN- ECOSOC');
INSERT INTO memberships (institution, year_commenced, last_renewed_year, renewed_label, status, reporting_cycle, renewal_cycle, fee_amount, fee_period, last_report_on, notes, created_by) SELECT 'AFIC', NULL, 2026, NULL, 'active', 'N/A', 'Annual ($100)', 100, 'annual', NULL, NULL, @import_user WHERE NOT EXISTS (SELECT 1 FROM memberships WHERE institution = 'AFIC');
INSERT INTO memberships (institution, year_commenced, last_renewed_year, renewed_label, status, reporting_cycle, renewal_cycle, fee_amount, fee_period, last_report_on, notes, created_by) SELECT 'GFMD', 2023, NULL, 'Never', 'lapsed', 'N/A', 'Annual ($400)', 400, 'annual', NULL, NULL, @import_user WHERE NOT EXISTS (SELECT 1 FROM memberships WHERE institution = 'GFMD');
INSERT INTO memberships (institution, year_commenced, last_renewed_year, renewed_label, status, reporting_cycle, renewal_cycle, fee_amount, fee_period, last_report_on, notes, created_by) SELECT 'AFEX', NULL, NULL, NULL, 'not_applicable', 'N/A', 'one-time', NULL, 'one_time', NULL, NULL, @import_user WHERE NOT EXISTS (SELECT 1 FROM memberships WHERE institution = 'AFEX');
INSERT INTO memberships (institution, year_commenced, last_renewed_year, renewed_label, status, reporting_cycle, renewal_cycle, fee_amount, fee_period, last_report_on, notes, created_by) SELECT 'IFEX', NULL, NULL, NULL, 'not_applicable', 'N/A', 'one-time', NULL, 'one_time', NULL, NULL, @import_user WHERE NOT EXISTS (SELECT 1 FROM memberships WHERE institution = 'IFEX');
INSERT INTO memberships (institution, year_commenced, last_renewed_year, renewed_label, status, reporting_cycle, renewal_cycle, fee_amount, fee_period, last_report_on, notes, created_by) SELECT 'The Chronicle of Philanthropy', 2026, NULL, '-', 'active', 'N/A', 'Annual ($376)', 376, 'annual', NULL, NULL, @import_user WHERE NOT EXISTS (SELECT 1 FROM memberships WHERE institution = 'The Chronicle of Philanthropy');
INSERT INTO memberships (institution, year_commenced, last_renewed_year, renewed_label, status, reporting_cycle, renewal_cycle, fee_amount, fee_period, last_report_on, notes, created_by) SELECT 'ECOWAS', NULL, NULL, '-', 'renewal_due', 'N/A', '4 years', NULL, 'multi_year', NULL, NULL, @import_user WHERE NOT EXISTS (SELECT 1 FROM memberships WHERE institution = 'ECOWAS');
INSERT INTO memberships (institution, year_commenced, last_renewed_year, renewed_label, status, reporting_cycle, renewal_cycle, fee_amount, fee_period, last_report_on, notes, created_by) SELECT 'SAMS.gov', NULL, NULL, NULL, 'unknown', NULL, NULL, NULL, NULL, NULL, NULL, @import_user WHERE NOT EXISTS (SELECT 1 FROM memberships WHERE institution = 'SAMS.gov');
INSERT INTO memberships (institution, year_commenced, last_renewed_year, renewed_label, status, reporting_cycle, renewal_cycle, fee_amount, fee_period, last_report_on, notes, created_by) SELECT 'Grants.gov', NULL, NULL, NULL, 'unknown', NULL, NULL, NULL, NULL, NULL, NULL, @import_user WHERE NOT EXISTS (SELECT 1 FROM memberships WHERE institution = 'Grants.gov');
INSERT INTO memberships (institution, year_commenced, last_renewed_year, renewed_label, status, reporting_cycle, renewal_cycle, fee_amount, fee_period, last_report_on, notes, created_by) SELECT 'EuropeAid Pador', NULL, NULL, NULL, 'unknown', NULL, NULL, NULL, NULL, NULL, NULL, @import_user WHERE NOT EXISTS (SELECT 1 FROM memberships WHERE institution = 'EuropeAid Pador');
INSERT INTO memberships (institution, year_commenced, last_renewed_year, renewed_label, status, reporting_cycle, renewal_cycle, fee_amount, fee_period, last_report_on, notes, created_by) SELECT 'Indico', NULL, NULL, NULL, 'unknown', NULL, NULL, NULL, NULL, NULL, NULL, @import_user WHERE NOT EXISTS (SELECT 1 FROM memberships WHERE institution = 'Indico');
INSERT INTO memberships (institution, year_commenced, last_renewed_year, renewed_label, status, reporting_cycle, renewal_cycle, fee_amount, fee_period, last_report_on, notes, created_by) SELECT 'Zoom', NULL, NULL, NULL, 'unknown', NULL, NULL, NULL, NULL, NULL, NULL, @import_user WHERE NOT EXISTS (SELECT 1 FROM memberships WHERE institution = 'Zoom');
INSERT INTO memberships (institution, year_commenced, last_renewed_year, renewed_label, status, reporting_cycle, renewal_cycle, fee_amount, fee_period, last_report_on, notes, created_by) SELECT 'NGOsource ED for William and Flora Hewlett Foundation', 2026, NULL, NULL, 'unknown', NULL, NULL, NULL, NULL, NULL, 'Date in source file: 2026-07-01', @import_user WHERE NOT EXISTS (SELECT 1 FROM memberships WHERE institution = 'NGOsource ED for William and Flora Hewlett Foundation');
